apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bd-prometheus-clusterrole
  namespace: bd-prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy  
  - services
  - nodes/metrics
  - services/finalizers  
  - endpoints
  - pods
  - prometheusrules
  - servicemonitors
  - podmonitors
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]  
- nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
  verbs: ["get"]

