apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: bd-prometheus-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole  
  name: bd-prometheus-clusterrole  
subjects:
- kind: ServiceAccount
  name: bd-prometheus-sa
  namespace: bd-prometheus
