kind: Deployment
apiVersion: apps/v1
metadata:
  name: bd-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bd-monitoring
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bd-monitoring      
        business-project: ""
    spec:
      restartPolicy: Always
      serviceAccountName: bd-prometheus-sa
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: 300m
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          name: bd-monitoring
          ports:
            - containerPort: 9090
              protocol: TCP
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /status
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: "/status"
              port: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: storage-volume
              mountPath: /prometheus
          terminationMessagePolicy: File
          image: >-
            registry.hub.docker.com/prom/prometheus:v2.22.2
          args:
            - '--storage.tsdb.path=/prometheus/'
            - '--storage.tsdb.retention=24h'
            - '--config.file=/etc/prometheus/prometheus.yml'
      serviceAccount: bd-monitoring-sa
      volumes:
        - name: config-volume
          configMap:
            name: prometheus
            defaultMode: 420
        - name: storage-volume
          emptyDir: {}
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
