kind: Service
apiVersion: v1
metadata:
  name: bd-prometheus-svc
  annotations:
    prometheus.io/port: '9090'
    prometheus.io/scrape: 'true'
spec:
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: bd-monitoring
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}

